# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu22/LuckfoxPicoProBuildEnv/nrfnet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu22/LuckfoxPicoProBuildEnv/nrfnet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu22/LuckfoxPicoProBuildEnv/nrfnet/CMakeFiles /home/ubuntu22/LuckfoxPicoProBuildEnv/nrfnet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu22/LuckfoxPicoProBuildEnv/nrfnet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nrfnet

# Build rule for target.
nrfnet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nrfnet
.PHONY : nrfnet

# fast build rule for target.
nrfnet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/build
.PHONY : nrfnet/fast

src/layers/ack_handling_layer.o: src/layers/ack_handling_layer.cc.o
.PHONY : src/layers/ack_handling_layer.o

# target to build an object file
src/layers/ack_handling_layer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/ack_handling_layer.cc.o
.PHONY : src/layers/ack_handling_layer.cc.o

src/layers/ack_handling_layer.i: src/layers/ack_handling_layer.cc.i
.PHONY : src/layers/ack_handling_layer.i

# target to preprocess a source file
src/layers/ack_handling_layer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/ack_handling_layer.cc.i
.PHONY : src/layers/ack_handling_layer.cc.i

src/layers/ack_handling_layer.s: src/layers/ack_handling_layer.cc.s
.PHONY : src/layers/ack_handling_layer.s

# target to generate assembly for a file
src/layers/ack_handling_layer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/ack_handling_layer.cc.s
.PHONY : src/layers/ack_handling_layer.cc.s

src/layers/mesh_radio_interface.o: src/layers/mesh_radio_interface.cc.o
.PHONY : src/layers/mesh_radio_interface.o

# target to build an object file
src/layers/mesh_radio_interface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/mesh_radio_interface.cc.o
.PHONY : src/layers/mesh_radio_interface.cc.o

src/layers/mesh_radio_interface.i: src/layers/mesh_radio_interface.cc.i
.PHONY : src/layers/mesh_radio_interface.i

# target to preprocess a source file
src/layers/mesh_radio_interface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/mesh_radio_interface.cc.i
.PHONY : src/layers/mesh_radio_interface.cc.i

src/layers/mesh_radio_interface.s: src/layers/mesh_radio_interface.cc.s
.PHONY : src/layers/mesh_radio_interface.s

# target to generate assembly for a file
src/layers/mesh_radio_interface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/mesh_radio_interface.cc.s
.PHONY : src/layers/mesh_radio_interface.cc.s

src/layers/message_fragmentation_layer.o: src/layers/message_fragmentation_layer.cc.o
.PHONY : src/layers/message_fragmentation_layer.o

# target to build an object file
src/layers/message_fragmentation_layer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/message_fragmentation_layer.cc.o
.PHONY : src/layers/message_fragmentation_layer.cc.o

src/layers/message_fragmentation_layer.i: src/layers/message_fragmentation_layer.cc.i
.PHONY : src/layers/message_fragmentation_layer.i

# target to preprocess a source file
src/layers/message_fragmentation_layer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/message_fragmentation_layer.cc.i
.PHONY : src/layers/message_fragmentation_layer.cc.i

src/layers/message_fragmentation_layer.s: src/layers/message_fragmentation_layer.cc.s
.PHONY : src/layers/message_fragmentation_layer.s

# target to generate assembly for a file
src/layers/message_fragmentation_layer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/message_fragmentation_layer.cc.s
.PHONY : src/layers/message_fragmentation_layer.cc.s

src/layers/tunnel_interface.o: src/layers/tunnel_interface.cc.o
.PHONY : src/layers/tunnel_interface.o

# target to build an object file
src/layers/tunnel_interface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/tunnel_interface.cc.o
.PHONY : src/layers/tunnel_interface.cc.o

src/layers/tunnel_interface.i: src/layers/tunnel_interface.cc.i
.PHONY : src/layers/tunnel_interface.i

# target to preprocess a source file
src/layers/tunnel_interface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/tunnel_interface.cc.i
.PHONY : src/layers/tunnel_interface.cc.i

src/layers/tunnel_interface.s: src/layers/tunnel_interface.cc.s
.PHONY : src/layers/tunnel_interface.s

# target to generate assembly for a file
src/layers/tunnel_interface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/layers/tunnel_interface.cc.s
.PHONY : src/layers/tunnel_interface.cc.s

src/nerfnet_main.o: src/nerfnet_main.cc.o
.PHONY : src/nerfnet_main.o

# target to build an object file
src/nerfnet_main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/nerfnet_main.cc.o
.PHONY : src/nerfnet_main.cc.o

src/nerfnet_main.i: src/nerfnet_main.cc.i
.PHONY : src/nerfnet_main.i

# target to preprocess a source file
src/nerfnet_main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/nerfnet_main.cc.i
.PHONY : src/nerfnet_main.cc.i

src/nerfnet_main.s: src/nerfnet_main.cc.s
.PHONY : src/nerfnet_main.s

# target to generate assembly for a file
src/nerfnet_main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/nerfnet_main.cc.s
.PHONY : src/nerfnet_main.cc.s

src/primary_radio_interface.o: src/primary_radio_interface.cc.o
.PHONY : src/primary_radio_interface.o

# target to build an object file
src/primary_radio_interface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/primary_radio_interface.cc.o
.PHONY : src/primary_radio_interface.cc.o

src/primary_radio_interface.i: src/primary_radio_interface.cc.i
.PHONY : src/primary_radio_interface.i

# target to preprocess a source file
src/primary_radio_interface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/primary_radio_interface.cc.i
.PHONY : src/primary_radio_interface.cc.i

src/primary_radio_interface.s: src/primary_radio_interface.cc.s
.PHONY : src/primary_radio_interface.s

# target to generate assembly for a file
src/primary_radio_interface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/primary_radio_interface.cc.s
.PHONY : src/primary_radio_interface.cc.s

src/radio_interface.o: src/radio_interface.cc.o
.PHONY : src/radio_interface.o

# target to build an object file
src/radio_interface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/radio_interface.cc.o
.PHONY : src/radio_interface.cc.o

src/radio_interface.i: src/radio_interface.cc.i
.PHONY : src/radio_interface.i

# target to preprocess a source file
src/radio_interface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/radio_interface.cc.i
.PHONY : src/radio_interface.cc.i

src/radio_interface.s: src/radio_interface.cc.s
.PHONY : src/radio_interface.s

# target to generate assembly for a file
src/radio_interface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/radio_interface.cc.s
.PHONY : src/radio_interface.cc.s

src/secondary_radio_interface.o: src/secondary_radio_interface.cc.o
.PHONY : src/secondary_radio_interface.o

# target to build an object file
src/secondary_radio_interface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/secondary_radio_interface.cc.o
.PHONY : src/secondary_radio_interface.cc.o

src/secondary_radio_interface.i: src/secondary_radio_interface.cc.i
.PHONY : src/secondary_radio_interface.i

# target to preprocess a source file
src/secondary_radio_interface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/secondary_radio_interface.cc.i
.PHONY : src/secondary_radio_interface.cc.i

src/secondary_radio_interface.s: src/secondary_radio_interface.cc.s
.PHONY : src/secondary_radio_interface.s

# target to generate assembly for a file
src/secondary_radio_interface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/secondary_radio_interface.cc.s
.PHONY : src/secondary_radio_interface.cc.s

src/utils/config_parser.o: src/utils/config_parser.cc.o
.PHONY : src/utils/config_parser.o

# target to build an object file
src/utils/config_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/utils/config_parser.cc.o
.PHONY : src/utils/config_parser.cc.o

src/utils/config_parser.i: src/utils/config_parser.cc.i
.PHONY : src/utils/config_parser.i

# target to preprocess a source file
src/utils/config_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/utils/config_parser.cc.i
.PHONY : src/utils/config_parser.cc.i

src/utils/config_parser.s: src/utils/config_parser.cc.s
.PHONY : src/utils/config_parser.s

# target to generate assembly for a file
src/utils/config_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/utils/config_parser.cc.s
.PHONY : src/utils/config_parser.cc.s

src/utils/nrftime.o: src/utils/nrftime.cc.o
.PHONY : src/utils/nrftime.o

# target to build an object file
src/utils/nrftime.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/utils/nrftime.cc.o
.PHONY : src/utils/nrftime.cc.o

src/utils/nrftime.i: src/utils/nrftime.cc.i
.PHONY : src/utils/nrftime.i

# target to preprocess a source file
src/utils/nrftime.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/utils/nrftime.cc.i
.PHONY : src/utils/nrftime.cc.i

src/utils/nrftime.s: src/utils/nrftime.cc.s
.PHONY : src/utils/nrftime.s

# target to generate assembly for a file
src/utils/nrftime.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrfnet.dir/build.make CMakeFiles/nrfnet.dir/src/utils/nrftime.cc.s
.PHONY : src/utils/nrftime.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nrfnet"
	@echo "... src/layers/ack_handling_layer.o"
	@echo "... src/layers/ack_handling_layer.i"
	@echo "... src/layers/ack_handling_layer.s"
	@echo "... src/layers/mesh_radio_interface.o"
	@echo "... src/layers/mesh_radio_interface.i"
	@echo "... src/layers/mesh_radio_interface.s"
	@echo "... src/layers/message_fragmentation_layer.o"
	@echo "... src/layers/message_fragmentation_layer.i"
	@echo "... src/layers/message_fragmentation_layer.s"
	@echo "... src/layers/tunnel_interface.o"
	@echo "... src/layers/tunnel_interface.i"
	@echo "... src/layers/tunnel_interface.s"
	@echo "... src/nerfnet_main.o"
	@echo "... src/nerfnet_main.i"
	@echo "... src/nerfnet_main.s"
	@echo "... src/primary_radio_interface.o"
	@echo "... src/primary_radio_interface.i"
	@echo "... src/primary_radio_interface.s"
	@echo "... src/radio_interface.o"
	@echo "... src/radio_interface.i"
	@echo "... src/radio_interface.s"
	@echo "... src/secondary_radio_interface.o"
	@echo "... src/secondary_radio_interface.i"
	@echo "... src/secondary_radio_interface.s"
	@echo "... src/utils/config_parser.o"
	@echo "... src/utils/config_parser.i"
	@echo "... src/utils/config_parser.s"
	@echo "... src/utils/nrftime.o"
	@echo "... src/utils/nrftime.i"
	@echo "... src/utils/nrftime.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

